### ISSUE TITLE
error while Compile Octo

### ISSUE THREAD

**Issue by s-baklanov** [YottaDB/YDBDBMS#1]
cmake -DCMAKE_INSTALL_PREFIX=$ydb_dist/plugin .. 
cmake -DCMAKE_INSTALL_PREFIX=$ydb_dist/plugin ..
-- The C compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found BISON: /usr/bin/bison (found version "3.0.4")
-- Found FLEX: /usr/bin/flex (found version "2.6.4")
-- Found YOTTADB: /usr/local/lib/yottadb/r126/libyottadb.so
-- Found Readline: /usr/lib/x86_64-linux-gnu/libreadline.so
CMake Error at cmake/FindConfig.cmake:28 (MESSAGE):
  Could not find LibConfig header file!
Call Stack (most recent call first):
  src/CMakeLists.txt:17 (find_package)

-- Configuring incomplete, errors occurred!
See also "/tmp/YDBOcto-master/build/CMakeFiles/CMakeOutput.log".

help me please!

**Comment by ChristopherEdwards** [comment]
@s-baklanov This looks like the libconfig-devel or libconfig-dev package is missing on your system.

Also, GitHub is just a mirror for our project to see all that is going on please visit us on GitLab: https://gitlab.com/YottaDB/DBMS/YDBOcto

**Comment by s-baklanov** [comment]
Thank you very much for your answer
Indeed, the libconfig-devel package was not installed.
apt-get install libconfig-del # was successful
but then it turned out that libssl-dev is also not installed
I had to tinker with it
apt-get install libssl-dev # did not work
after installing the package manually, Octo was successfully compiled.
Octo launched. While it is not clear how to work with him. Can't even get out. Reprobeed STOP, EXIT, END
Maybe there is some other documentation on this. On the official website could not find.

**Comment by nars1** [comment]
@s-baklanov : Ctrl-D will terminate the process. Can you please create a new issue at https://gitlab.com/YottaDB/DBMS/YDBOcto/issues to let STOP/EXIT/END terminate the octo process. Thanks.
